### ISSUE TITLE
Recipe DB

### ISSUE THREAD

**Issue by wakkaluba** [ZergRael/RecipesCollector#1]
Hi there,

a database that lists all recipes in the game and tells where to get them would be a nice feature.
It is kinda similar to what recipe radar did.

**Comment by ZergRael** [comment]
Hello,

I'm not sure this would fit in the project as I would like to keep the recipe database as light as possible.
Furthermore it's already pretty hard to find all recipes IDs, so I cannot imagine how cumbersome it would get with locations.

I'm sorry this is not possible for now.
