### ISSUE TITLE
Show  Progress % of each profession.

### ISSUE THREAD

**Issue by caneff123** [ZergRael/RecipesCollector#3]
Is it possible to add progress of each profession you have, for example 190 ouf ot 220 recipes, Also showing full list of recipes you have and the ones you are missing. Similar to addon I used in private servers: ackis recipe list.

**Comment by ZergRael** [comment]
Hey,
Thanks for the suggestion, unfortunately I cannot add that as the recipe database I use is pretty rough and doesn't include a profession filter.
Sorry !
